name: Request Unity activation file

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  request:
    name: Generate .alf activation file
    runs-on: ubuntu-22.04
    steps:
      - name: Request manual activation file
        id: activation
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.62f1

      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: UnityActivationFile
          path: ${{ steps.activation.outputs.filePath }}
          retention-days: 7
